### ISSUE TITLE
Migration from 1.3.175 to 2.0.201 did not work 

### ISSUE THREAD

**Issue by osenbg** [manticore-projects/H2MigrationTool#1]
Hi,

trying to migrate from 1.3.175 to 2.0.201 comes up with following Exception 

----- 

Exception in thread "main" java.lang.Exception: Failed to migrate the database.
	at com.manticore.h2.H2MigrationTool.main(H2MigrationTool.java:1090)
Caused by: java.lang.Exception: Failed to write H2-1.3.175 database to script
	at com.manticore.h2.H2MigrationTool.migrate(H2MigrationTool.java:776)
	at com.manticore.h2.H2MigrationTool.main(H2MigrationTool.java:1066)
Caused by: java.lang.NoSuchMethodException: org.h2.tools.Script.process(java.sql.Connection, java.lang.String, java.lang.String, java.lang.String)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
	at com.manticore.h2.H2MigrationTool.writeScript(H2MigrationTool.java:626)
	at com.manticore.h2.H2MigrationTool.migrate(H2MigrationTool.java:765)
	... 1 more

**Comment by manticore-projects** [comment]
Thank you for reporting. It looks like 1.3.x did not have yet the
needed class for exporting to SQL Script.
I will investigated that and return back to you soonest.

**Comment by manticore-projects** [comment]
Solved via f41a413e54b27aa9ab4cff4c5ae38b7ce6585fe7.

**Comment by osenbg** [comment]
Hi Andreas,

thanks for update.
We give the new Version a quick try but failed on CLI because of that:
----
Only *.mv.db, *.sql, *.sql.gz or *.sql.zip files are supported
----
My test takes a native "page store" 1.3.176 database as input and a 2.0.201 as output 

Did i miss anything?

**Comment by manticore-projects** [comment]
Very likely an oversight on my end. Will look into that. Please try the UI which I have tested. Was not aware that anyone would actually use the CLI. Please bear with me.Sent from my Galaxy
-------- Original message --------From: osenbg ***@***.***> Date: 04/06/2021  13:24  (GMT+07:00) To: manticore-projects/H2MigrationTool ***@***.***> Cc: manticore-projects ***@***.***>, State change ***@***.***> Subject: Re: [manticore-projects/H2MigrationTool] Migration from 1.3.175 to
  2.0.201 did not work  (#1) 
Hi Andreas,
thanks for update.
We give the new Version a quick try but failed on CLI because of that:
Only *.mv.db, *.sql, *.sql.gz or *.sql.zip files are supported
My test takes a native "page store" 1.3.176 database as input and a 2.0.201 as output
Did i miss anything?
