### ISSUE TITLE
Error: the database is read only [90097-196]

### ISSUE THREAD

**Issue by JavaOPs** [manticore-projects/H2MigrationTool#7]
Error: the database is read only [90097-196]
At the same time can connect to db and modify it by DB-Tools.

**Comment by JavaOPs** [comment]
SEVERE: Failed to write H2-1.4.196 database to script
org.h2.jdbc.JdbcSQLException: ???? ?????? ???????? ?????? ?? ??????
The database is read only [90097-196]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.message.DbException.get(DbException.java:144)
        at org.h2.engine.Database.checkWritingAllowed(Database.java:1935)
        at org.h2.store.FileStore.checkWritingAllowed(FileStore.java:161)
        at org.h2.store.FileStore.write(FileStore.java:325)
        at org.h2.store.PageStore.writePage(PageStore.java:1369)
        at org.h2.store.PageLog.recover(PageLog.java:307)
        at org.h2.store.PageStore.recover(PageStore.java:1395)
        at org.h2.store.PageStore.openExisting(PageStore.java:368)
        at org.h2.store.PageStore.open(PageStore.java:289)
        at org.h2.engine.Database.getPageStore(Database.java:2490)
        at org.h2.engine.Database.open(Database.java:697)
        at org.h2.engine.Database.openDatabase(Database.java:276)
        at org.h2.engine.Database.<init>(Database.java:270)
        at org.h2.engine.Engine.openSession(Engine.java:64)
        at org.h2.engine.Engine.openSession(Engine.java:176)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
        at org.h2.engine.Engine.createSession(Engine.java:137)
        at org.h2.engine.Engine.createSession(Engine.java:27)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
        at org.h2.Driver.connect(Driver.java:69)
        at com.manticore.h2.H2MigrationTool.writeScript(H2MigrationTool.java:599)
        at com.manticore.h2.H2MigrationTool.migrate(H2MigrationTool.java:742)
        at com.manticore.h2.H2MigrationTool.main(H2MigrationTool.java:1031)

**Comment by manticore-projects** [comment]
Difficult to say anything on that, as this comes from the H2 driver directly.
Can you share the DB maybe?

**Comment by manticore-projects** [comment]
No further questions asked, closing.
