### ISSUE TITLE
No H2 driver found for requestion version 1.4.197

### ISSUE THREAD

**Issue by ctonsing** [manticore-projects/H2MigrationTool#8]
Good day,

firstly, thank you for this tool you have created. I'm trying to run from command line, upgrading a 1.4.197 db to 2.1.214. I've downloaded the respective jar files and put them in a directory. I use the -l / --lib-dir flag to point to this directory when i run the command, but I get the following error:

```
Exception in thread "main" java.lang.Exception: Failed to migrate the database.
	at com.manticore.h2.H2MigrationTool.main(H2MigrationTool.java:1149)
Caused by: java.lang.Exception: No H2 driver found for requestion version 1.4.197
	at com.manticore.h2.H2MigrationTool.getDriverRecord(H2MigrationTool.java:620)
	at com.manticore.h2.H2MigrationTool.getDriverRecord(H2MigrationTool.java:626)
	at com.manticore.h2.H2MigrationTool.migrate(H2MigrationTool.java:834)
	at com.manticore.h2.H2MigrationTool.main(H2MigrationTool.java:1142)
```
I'm using the current latest release of your tool, v1.2.
Could you please let me know what the problem could be? How can I let the tool see the jars?

**Comment by dlmcpaul** [comment]
@ctonsing It is possible the jar files are corrupt.  That was my issue when I got that error.

But since a number of jars are built in try using them instead of downloaded ones
ie -f 1.4.200 -t 2.1.210 should work with needing anything else

**Comment by manticore-projects** [comment]
Greetings, this has been fixed and [you can try it online here.](https://h2migrationtool.manticore-projects.com)
